version: "3.8"
name: e-learning-plattform

networks:
  shared_network:
    driver: bridge

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      # - --encryptionEnv
      # - ENCRYPTION
    # environment:
      # ENCRYPTION: example
    ports:
      - "8080:8090"
    volumes:
      - ./local/pb/data:/pb_data
      # - ./local/pb/public:/pb_public
      # - ./local/pb/hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 2
    networks:
      - shared_network

  aisearch:
    build:
      context: .
      dockerfile: ./aisearch/Dockerfile
      args:
        DATAPROVIDER_USER: ${DATAPROVIDER_USER}
        DATAPROVIDER_PASSWORD: ${DATAPROVIDER_PASSWORD}
        DATAPROVIDER_URL: ${DATAPROVIDER_URL}
        BASE_LANGUAGE: ${VITE_BASE_LANGUAGE}
        DEBUG: ${DEBUG}
    container_name: aisearch
    restart: unless-stopped
    ports:
      - "8091:8000"
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - shared_network
  
  editor:
    build:
      context: ./editor
      args:
        VITE_BASE_LANGUAGE: ${VITE_BASE_LANGUAGE}
        VITE_AVAILABLE_LANGUAGES: ${VITE_AVAILABLE_LANGUAGES}
        VITE_DOCUMENT_DATASOURCE: ${VITE_DOCUMENT_DATASOURCE}
        VITE_POCKETBASE_URL: ${VITE_POCKETBASE_URL}
        VITE_OPENAI_KEY: ${VITE_OPENAI_KEY}
        VITE_VIDEOCONVERTER_URL: ${VITE_VIDEOCONVERTER_URL}
        VITE_TEMPLATE_START_LOGO: ${VITE_TEMPLATE_START_LOGO}
        VITE_TEMPLATE_WELCOME_SLOGAN: ${VITE_TEMPLATE_WELCOME_SLOGAN}
        VITE_TEMPLATE_APP_NAME: ${VITE_TEMPLATE_APP_NAME}
        VITE_TEMPLATE_LOGO_URL: ${VITE_TEMPLATE_LOGO_URL}
    ports:
      - "9000:80"

  video-convert-service-preprocess:
    build:
      context: .
      dockerfile: ./video-convert/docker/Dockerfile.video-convert.service
    volumes:
      - ./video-convert:/app
    restart: always
    # cpus: 2
    depends_on:
      pocketbase:
        condition: service_healthy

  video-convert-service:
    build:
      context: .
      dockerfile: ./video-convert/docker/Dockerfile.preprocess.service
    volumes:
      - ./video-convert:/app
    restart: always
    # cpus: 2
    depends_on:
      pocketbase:
        condition: service_healthy

  user-verification:
    build:
      context: .
      dockerfile: ./video-convert/docker/Dockerfile.user-verification.service
    volumes:
      - ./video-convert:/app
    restart: on-failure
    # cpus: 2
    depends_on:
      pocketbase:
        condition: service_healthy
